// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl9pgPkVEmCr7SUElsEN1-7EZldixQTa4',
    appId: '1:95221063243:web:7b32f2825cbed07b8777ce',
    messagingSenderId: '95221063243',
    projectId: 'cinescope-9d8c0',
    authDomain: 'cinescope-9d8c0.firebaseapp.com',
    storageBucket: 'cinescope-9d8c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXdkDaX6pqD4bpLMtgJ7PmThyo-I0Vw3U',
    appId: '1:95221063243:android:7906aca0ec8571f68777ce',
    messagingSenderId: '95221063243',
    projectId: 'cinescope-9d8c0',
    storageBucket: 'cinescope-9d8c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo_PngAVpL-LS7WqFopsKKa5mW7sb5XB8',
    appId: '1:95221063243:ios:ebf36e8d2331608b8777ce',
    messagingSenderId: '95221063243',
    projectId: 'cinescope-9d8c0',
    storageBucket: 'cinescope-9d8c0.appspot.com',
    iosClientId: '95221063243-rlbhvp20bonson8op66efqgc33ssbv1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinescope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo_PngAVpL-LS7WqFopsKKa5mW7sb5XB8',
    appId: '1:95221063243:ios:ebf36e8d2331608b8777ce',
    messagingSenderId: '95221063243',
    projectId: 'cinescope-9d8c0',
    storageBucket: 'cinescope-9d8c0.appspot.com',
    iosClientId: '95221063243-rlbhvp20bonson8op66efqgc33ssbv1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinescope',
  );
}
