// Mocks generated by Mockito 5.4.0 from annotations
// in cinescope/test/view/generic_film_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;
import 'dart:ui' as _i7;

import 'package:cinescope/model/film.dart' as _i4;
import 'package:cinescope/model/providers/film_provider.dart' as _i8;
import 'package:cinescope/model/providers/watchlist_provider.dart' as _i6;
import 'package:cinescope/model/watchlist.dart' as _i3;
import 'package:flutter/material.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStreamController_0<T> extends _i1.SmartFake
    implements _i2.StreamController<T> {
  _FakeStreamController_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWatchlist_1 extends _i1.SmartFake implements _i3.Watchlist {
  _FakeWatchlist_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFilm_2 extends _i1.SmartFake implements _i4.Film {
  _FakeFilm_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i5.NavigatorObserver {
  @override
  void didPush(
    _i5.Route<dynamic>? route,
    _i5.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPush,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void didPop(
    _i5.Route<dynamic>? route,
    _i5.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPop,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void didRemove(
    _i5.Route<dynamic>? route,
    _i5.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didRemove,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void didReplace({
    _i5.Route<dynamic>? newRoute,
    _i5.Route<dynamic>? oldRoute,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #didReplace,
          [],
          {
            #newRoute: newRoute,
            #oldRoute: oldRoute,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  void didStartUserGesture(
    _i5.Route<dynamic>? route,
    _i5.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didStartUserGesture,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void didStopUserGesture() => super.noSuchMethod(
        Invocation.method(
          #didStopUserGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WatchlistProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistProvider extends _i1.Mock implements _i6.WatchlistProvider {
  @override
  _i2.StreamController<bool> get loadedController => (super.noSuchMethod(
        Invocation.getter(#loadedController),
        returnValue: _FakeStreamController_0<bool>(
          this,
          Invocation.getter(#loadedController),
        ),
        returnValueForMissingStub: _FakeStreamController_0<bool>(
          this,
          Invocation.getter(#loadedController),
        ),
      ) as _i2.StreamController<bool>);
  @override
  bool get lastLoaded => (super.noSuchMethod(
        Invocation.getter(#lastLoaded),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  set lastLoaded(bool? _lastLoaded) => super.noSuchMethod(
        Invocation.setter(
          #lastLoaded,
          _lastLoaded,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i2.Stream<bool> get loaded => (super.noSuchMethod(
        Invocation.getter(#loaded),
        returnValue: _i2.Stream<bool>.empty(),
        returnValueForMissingStub: _i2.Stream<bool>.empty(),
      ) as _i2.Stream<bool>);
  @override
  set loaded(_i2.Stream<bool>? _loaded) => super.noSuchMethod(
        Invocation.setter(
          #loaded,
          _loaded,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i3.Watchlist getWatchlist() => (super.noSuchMethod(
        Invocation.method(
          #getWatchlist,
          [],
        ),
        returnValue: _FakeWatchlist_1(
          this,
          Invocation.method(
            #getWatchlist,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeWatchlist_1(
          this,
          Invocation.method(
            #getWatchlist,
            [],
          ),
        ),
      ) as _i3.Watchlist);
  @override
  _i2.Future<void> addFilmToWatchlist(String? filmId) => (super.noSuchMethod(
        Invocation.method(
          #addFilmToWatchlist,
          [filmId],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);
  @override
  _i2.Future<void> removeFilmFromWatchlist(_i4.Film? film) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFilmFromWatchlist,
          [film],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);
  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FilmProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilmProvider extends _i1.Mock implements _i8.FilmProvider {
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i2.Future<_i4.Film> getFilm(String? filmId) => (super.noSuchMethod(
        Invocation.method(
          #getFilm,
          [filmId],
        ),
        returnValue: _i2.Future<_i4.Film>.value(_FakeFilm_2(
          this,
          Invocation.method(
            #getFilm,
            [filmId],
          ),
        )),
        returnValueForMissingStub: _i2.Future<_i4.Film>.value(_FakeFilm_2(
          this,
          Invocation.method(
            #getFilm,
            [filmId],
          ),
        )),
      ) as _i2.Future<_i4.Film>);
  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
